name = "BalansBot"
uuid = "be01283e-713e-4ff7-bbef-0b8c7a1aa0e4"
version = "0.1.0"
authors = ["Ben Chung <benjamin.chung@juliahub.com>"]

[deps]
BalansBotDrivers = "825443c2-6a71-43bb-a614-9f2bf9e50e56"
CDRSerialization = "cbcadc0d-0faf-4c71-82b5-fceb8cc36223"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IDLParser = "817e8c30-d1ad-4896-85b5-1c4c82b7999b"
Libevdev = "16d368ef-f5da-4971-84d3-b8145f955bda"
PIOLib = "a21b0171-75fd-41b6-8640-f97fa3fa9a76"
PIOLib_jll = "71578703-7aff-5c16-bbae-7ba9c160b2b9"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ROSMessages = "745bd5ac-df70-4edb-8655-498bbbb894cf"
ROSNode = "bb9e268e-7981-4227-9ebf-b0919ec29e7a"
ROSZenoh = "02c87683-9d8e-4267-bbb6-13e61ef8b9a5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Zenoh = "b742139f-8771-480b-a9b2-33222b45d29b"

[sources]
CDRSerialization = {url = "https://github.com/BenChung/CDRSerialization.jl"}
IDLParser = {subdir = "IDLParser", url = "https://github.com/BenChung/IDLParser.jl"}
Libevdev = {url = "https://github.com/JuliaComputing/Libevdev.jl"}
PIOLib = {url = "https://github.com/JuliaComputing/PIOLib.jl"}
ROSMessages = {subdir = "ROSMessages", url = "https://github.com/BenChung/IDLParser.jl"}
ROSNode = {subdir = "ROSNode", url = "https://github.com/BenChung/IDLParser.jl"}
ROSZenoh = {subdir = "ROSZenoh", url = "https://github.com/BenChung/IDLParser.jl"}
Zenoh = {url = "https://github.com/BenChung/Zenoh.jl"}

[compat]
Configurations = "0.17.6"
Dates = "1.11.0"
IDLParser = "1.0.0"
PrecompileTools = "1.3.4"
ROSMessages = "0.1.0"
ROSNode = "0.1.0"
ROSZenoh = "0.1.0"
StaticArrays = "1.9.18"
StatsBase = "0.34.11"
